### ISSUE TITLE
Address the ASLRecognition screen's tests failing on some aspect ratios

### ISSUE THREAD

**Issue by ThomasMPont** [Signify-epfl/signify-app#132]
Address the test allComponentsAreDisplayed from ASLRecognitionTest failing on certain devices.
![Image](https://github.com/user-attachments/assets/21ff743b-7a63-478e-b621-958d2b3c1e34)

I believe this to be due to the test not being robust to larger aspect ratios. Since the screen is scrollable, a quick fix could be to have the test scroll to elements before looking for them.

**Comment by SaFouNaldo** [comment]
Hi Thomas,
I don't understand/ can't see the aspect you are referring to. 
Could give more details on this task and/or an example ?
Thanks a lot

**Comment by ThomasMPont** [comment]
> Hi Thomas, I don't understand/ can't see the aspect you are referring to. Could you give more details on this task and/or an example ? Thanks a lot

I opened this issue in a rush. Its description will be updated shortly.
