### ISSUE TITLE
Improve the test coverage of ChallengeHistoryScreen.kt

### ISSUE THREAD

**Issue by GRGool** [Signify-epfl/signify-app#149]
For now we have 78% coverage. However, if we can improve this to 90%, it will be better.

**Comment by GRGool** [comment]
Seems to be issues with how jacoco handles scaffolds. Removing the scaffold instantly gives 98% coverage. LoginScreen.kt has a scaffold aswell and suffers the same problem where you miss branches and it hurts the coverage. Currently figuring out how to properly test scaffolds.

**Comment by ziyadbagh** [comment]
Hello @GRGool, I noticed this issue has been open since last week and hasn’t moved into development. Are you currently working on it, or should it be closed?

**Comment by GRGool** [comment]
Should be closed. As indicated in solar flare this is sufficiently covered and the issue lied in branches so branch coverage.
