### ISSUE TITLE
Adapt the profile screen's design on Figma

### ISSUE THREAD

**Issue by NBCCF025** [Signify-epfl/signify-app#161]
When going to the friends list or the statistics, it is important to know from which person the user is looking.

For example: I can go to the statistics of one of my friend and the screen put his username and his profile picture at the top, so I know that I am looking at his stats and not mine.

Doing this change now is important as, we could directly implement this new UI desgin and create/use a composable from the Utils.kt file and lower the duplication code.

**Comment by ThomasMPont** [comment]
Since this was moved to `In Review`, I'm assuming you are done with the task.
If so, could you clarify what exactly you have changed on Figma? (you could link a screenshot) I'm not sure I understand what you expect us to review.

**Comment by NBCCF025** [comment]
You are right, I should have mentioned what were the update in the design.

I modified the FriendsListScreen and the MyStatsScreen to have the basic user information so that the user know from which point of vue he is seeing these screens (for example the user goes to the statistics of one of his friends).
By seeing the following screenshots, I remark that the edit of the profile picture and the edit of the username are swaped in the SettingsScreen, but this change doesn't come from me.

I put it in `In Review` so that everyone can see that the design has changed.

**Old version:**
![Image](https://github.com/user-attachments/assets/78d78987-5429-4fdc-abbb-5eb2a4c1830b)


**New version:**
![Image](https://github.com/user-attachments/assets/b8dabb7d-a2b1-4fd6-84ee-298f9f0e6576)

**Comment by ziyadbagh** [comment]
I don't think a user should be able to view a friend's statistics. Additionally, I'm still unclear about the recent changes made in Figma; it seems like there are quite a few repetitive elements, like the profile photo appearing on four screens along with the user ID and username.

**Comment by NBCCF025** [comment]
I propose we discuss that during the sprint meeting to have the opinion of each group member. Then modification will occur if needed.
