### ISSUE TITLE
Resolve the miss of coverage on sonarcloud

### ISSUE THREAD

**Issue by NBCCF025** [Signify-epfl/signify-app#173]
Add the following two lines in gradle/libs.versions.toml that were removed in the PR #160.

sonar = "4.4.1.3373"
sonar = { id = "org.sonarqube", version.ref = "sonar" }

This two lines are necessary to have the coverage on sonarcloud.

**Comment by ThomasMPont** [comment]
I've created a separate task to have this be fixed in a standalone PR. Please refrain from bundling multiple unrelated issues in a single PR, even when the change is this small. I'll close this since it has been replaced.
