### ISSUE TITLE
Disable the landscape phone mode

### ISSUE THREAD

**Issue by SaFouNaldo** [Signify-epfl/signify-app#183]
- **What Changed**: Disabled landscape mode for phone devices across the application.
- **Reason**: The app is designed primarily for portrait orientation, and landscape mode introduces unintended layout issues and inconsistencies that degrade the user experience. Since landscape mode is unnecessary for the app's functionality, this change helps maintain a consistent and focused UI.

**Comment by ThomasMPont** [comment]
Looks like this issue was meant to be deleted along with its task. I'll do it now.
