### ISSUE TITLE
Implement the offlineMode

### ISSUE THREAD

**Issue by SaFouNaldo** [Signify-epfl/signify-app#272]
## Objective
- Introduce an Offline Mode to ensure that users can access specific app features (e.g., the Practice Epic) without requiring an internet connection while restricting access to user-related screens until the user logs in.

**Comment by ThomasMPont** [comment]
You had marked this task as `In Development`. Can you explain what this is? I can't imagine how this broad set of features can be a 4h task.

**Comment by SaFouNaldo** [comment]
I didn't give a detailed description for that but basically : 
- The feature is simple as a first step chich is simply creating a button that get you to the HomeScreen by clicking on it.
- But what is really complicated is that you have to take into account to either remove the dependency user or create a barrier from the guest user and the screens that depends to the users propreties. This two solution takes a lot of time because it changes a lot of classes (adding conditions, new functions, update tests ...)
