### ISSUE TITLE
Move `MockDependencyProvider.kt` into `main/`

### ISSUE THREAD

**Issue by ThomasMPont** [Signify-epfl/signify-app#331]
Move `MockDependencyProvider.kt` from `test/` into a fitting package of `main/`.
This is difficult at the moment since the class uses Mockito.
This should be done after all dependency mocks are merged.

**Comment by SaFouNaldo** [comment]
I'm assaigning my self, as I need to use the MockDependencyProvider.kt. 
The modification about mocking can be done later.
