### ISSUE TITLE
Optimize and clean up the implementation of the practice screen

### ISSUE THREAD

**Issue by SaFouNaldo** [Signify-epfl/signify-app#54]

**Comment by ThomasMPont** [comment]
What are you calling the main screen? Is it the home, camera or some other screen?
I think you should rename this task for clarity.

**Comment by ThomasMPont** [comment]
This being marked as a 10 hour task, it should at least have a detailed description, and maybe also be split into a couple smaller tasks.

**Comment by SaFouNaldo** [comment]
> What are you calling the main screen? Is it the home, camera or some other screen? I think you should rename this task for clarity.

Hello Thomas,
The Main Screen is the Main Screen class(Or the screen where the main aim/purpose of the app is done aka ASL recognition).
As I'm referring to the main screen class(This is how it's nammed for now), I don't think changing the name will be clearer.

**Comment by ThomasMPont** [comment]
> Hello Thomas, The Main Screen is the Main Screen class(Or the screen where the main aim/purpose of the app is done aka ASL recognition). As I'm referring to the main screen class(This is how it's nammed for now), I don't think changing the name will be clearer.

Okay, that's what I assumed, it hasn't been called that anywhere else than in the code though. Maybe we should consider a refactor of either the class name or the user stories. I believe others such as the coaches might also find this naming convention confusing.

**Comment by ThomasMPont** [comment]
> It's a 10h task because the debugg process is difficult and tiring. There is no detailed desciption to provide except the fact of minimizing the inference time of processing the landmarks for each frame/Imageproxy(around 1s for now).

Maybe the description could at least explain the motivation behind these changes. I am having a justifyably hard time understanding why they are needed.

**Comment by SaFouNaldo** [comment]
> > It's a 10h task because the debugg process is difficult and tiring. There is no detailed desciption to provide except the fact of minimizing the inference time of processing the landmarks for each frame/Imageproxy(around 1s for now).
> 
> Maybe the description could at least explain the motivation behind these changes. I am having a justifyably hard time understanding why they are needed.

They will be explanations during the related PR that I would do during the week.

**Comment by ThomasMPont** [comment]
> They will be explanations during the related PR that I would do during the week.

Do as you wish, but adding a description early could save you unnecessary work, if someone disagrees with your changes before you even implement them.

**Comment by ThomasMPont** [comment]
Is it okay if I rename this to `Optimize and clean up the implementation of the camera feedback screen? That's what it's called on Figma and refered to as in it's user story.
